[bridgestan]
git-tree-sha1 = "24e824271f34289cc8b1ecdba62be2d80a4f9c78"
lazy = true

    [[bridgestan.download]]
    sha256 = "44270abc2d0103eac97ec800115ef748a8ffbbeb006e6ba9de696f876f3400e2"
    url = "https://github.com/roualdes/bridgestan/releases/download/v2.2.0/bridgestan-2.2.0.tar.gz"
